[workspace]
resolver = "2"

members = [
    "antsforaging",
    "flockers",
    "forestfire",
    "forestfire_bayesian",
    "schelling",
    "sir_ga_exploration",
    "sugarscape",
    "template",
    "virusnetwork",
    "wolfsheepgrass",
]
